package io.ohmyluke.project;

public enum ProjectScanNotice {
    ENTRY_LIMIT_REACHED,
    TOTAL_BYTES_LIMIT_REACHED,
    DEPTH_LIMIT_REACHED,
    SENSITIVE_PATH_SKIPPED,
    GENERATED_PATH_SKIPPED,
    BINARY_FILE_SKIPPED,
    LARGE_FILE_SKIPPED,
    SYMBOLIC_LINK_SKIPPED,
    UNSUPPORTED_FILE_SKIPPED,
    MANIFEST_PARSE_FAILED
}
